server {
    listen 80;
    root /var/www/html/public;
    index index.php;

    
    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|css|js|woff|woff2|ttf)$ {
        try_files $uri =404;
        expires max;
        add_header Cache-Control "public, immutable";
    }

   
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}